import { ATTRIBUTION, HOLETYPE_LABELS, LICENCE_URL, SOURCE_NOTE } from "@/lib/constants";
import { methodName, rankPhrase, reportUrl } from "@/lib/reports";
import type { Brief } from "@/app/types";

/**
 * Exports. Everything here is a re-rendering of the stored brief -- no new
 * queries, no new claims -- in shapes a geologist can paste into their own
 * work: the section G table the department asks for, the inventory, the whole
 * document. CC BY 4.0 requires the attribution to travel with the data, so
 * every file carries it.
 */

export type ExportMeta = { title?: string | null; permalink?: string; createdAt?: string | null };

const n = (x: number | null | undefined) => (x ?? 0).toLocaleString("en-AU");
const EXCLUDED = ["WATER_BORE", "COSTEAN", "UNKNOWN", "OTHER"];

/** RFC 4180 escaping. */
export function csvCell(v: unknown): string {
  if (v == null) return "";
  const s = String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
export function csv(rows: unknown[][]): string {
  return rows.map((r) => r.map(csvCell).join(",")).join("\r\n") + "\r\n";
}

export function attributionLines(brief: Brief, meta: ExportMeta): string[] {
  return [
    `${ATTRIBUTION}, used under CC BY 4.0 (${LICENCE_URL}).`,
    `Generated by wamex-explorer${meta.permalink ? ` — ${meta.permalink}` : ""}` +
      `${brief.meta.dataVersion ? `, from department data extracted ${brief.meta.dataVersion}` : ""}` +
      `${meta.createdAt ? `, on ${meta.createdAt.slice(0, 10)}` : ""}. Structured database query only; no language model.`,
  ];
}

/** Section G: "Previous exploration activities", one row per operator, with A-numbers. */
export function timelineRows(brief: Brief): { header: string[]; rows: (string | number)[][] } {
  return {
    header: ["From", "To", "Operator", "Reports", "Holes", "Target commodities", "A-numbers"],
    rows: brief.timeline.map((t) => [
      t.first_year ?? "", t.last_year ?? "", t.operator, t.reports, t.holes,
      t.commodities.map((c) => c.toLowerCase()).join("; "),
      t.anumbers.map((a) => `A${a}`).join(" "),
    ]),
  };
}

export function timelineCsv(brief: Brief, meta: ExportMeta): string {
  const { header, rows } = timelineRows(brief);
  return attributionLines(brief, meta).map((l) => `# ${l}`).join("\r\n") + "\r\n" + csv([header, ...rows]);
}

export function reportsCsv(brief: Brief, meta: ExportMeta): string {
  const header = ["A-number", "Year", "Type", "Operator", "Title", "Covers % of area", "Footprint km2", "URL", "Abstract"];
  const rows = brief.reports.map((r) => [
    `A${r.anumber}`, r.report_year ?? "", r.report_type ?? "", r.operator ?? "", r.title ?? "",
    r.coverage_pct ?? "", r.footprint_km2 ?? "", reportUrl(r), r.abstract_full ?? r.abstract_short ?? "",
  ]);
  return attributionLines(brief, meta).map((l) => `# ${l}`).join("\r\n") + "\r\n" + csv([header, ...rows]);
}

function mdTable(header: string[], rows: (string | number | null)[][]): string {
  const esc = (v: unknown) => String(v ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
  return [
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${r.map(esc).join(" | ")} |`),
  ].join("\n");
}

export function timelineMarkdown(brief: Brief, meta: ExportMeta): string {
  const { header, rows } = timelineRows(brief);
  const linked = rows.map((r) => [...r.slice(0, 6), String(r[6]).split(" ").filter(Boolean)
    .map((a) => `[${a}](https://wamex.dmp.wa.gov.au/Wamex/Search/ReportDetails?ANumber=${a.slice(1)})`).join(" ")]);
  return [
    `## Previous exploration activities`,
    ``,
    `_Open-file WAMEX reports intersecting ${meta.title ?? "the area"}, by operator, oldest first. ` +
      `Holes are collars attributed to that operator name in the drillhole register._`,
    ``,
    mdTable(header, linked),
    ``,
    ...attributionLines(brief, meta).map((l) => `_${l}_`),
    ``,
  ].join("\n");
}

/** The whole document as Markdown, section for section. */
export function briefMarkdown(brief: Brief, meta: ExportMeta): string {
  const s = brief.summary, p = brief.period, cov = brief.coverage;
  const expl = brief.holeTypes.filter((h) => !EXCLUDED.includes(h.holetype));
  const totalM = expl.reduce((a, h) => a + (h.total_m ?? 0), 0);
  const out: string[] = [];
  const title = meta.title ?? `${s.area_km2} km² of ground`;
  const [lon, lat] = brief.centroid ?? [NaN, NaN];

  out.push(`# Ground history brief — ${title}`, ``);
  out.push(`${s.area_km2} km²` + (Number.isFinite(lat) ? ` · centre ${Math.abs(lat).toFixed(4)}°S ${lon.toFixed(4)}°E` : "") +
    (p.first_year ? ` · open-file record ${p.first_year}–${p.last_year}` : ""), ``);
  if (meta.permalink) out.push(`Permalink: ${meta.permalink}`, ``);

  out.push(`## 1. At a glance`, ``);
  out.push(`- Open-file reports: **${n(s.report_count)}**`);
  out.push(`- Drillhole collars: **${n(s.hole_count)}** (${n(s.exploration_hole_count)} exploration holes${totalM ? `, ${n(totalM)} m` : ""})`);
  if (p.first_year) out.push(`- Years on record: **${p.first_year}–${p.last_year}**`);
  if (brief.gapDecades.length) out.push(`- No report dated to the ${brief.gapDecades.map((d) => `${d}s`).join(", ")}`);
  if (brief.baseline && brief.baseline.metrics.holes_per_km2.value > 0) {
    const m = brief.baseline.metrics;
    out.push(`- Against the ${n(brief.baseline.n_cells)} ${brief.baseline.cell_km} km squares in WA with any exploration drilling: ` +
      `${rankPhrase(m.holes_per_km2.rank)} for holes, ${rankPhrase(m.metres_per_km2.rank)} for metres, ${rankPhrase(m.reports_per_km2.rank)} for reports`);
  }
  out.push(``);

  out.push(`## 2. Exploration timeline (previous exploration activities)`, ``);
  const tl = timelineRows(brief);
  out.push(tl.rows.length ? mdTable(tl.header, tl.rows) : `_No operator is named on any report intersecting this area._`, ``);
  if (brief.reportsByDecade.length) {
    out.push(`Reports lodged by decade: ` + brief.reportsByDecade.map((d) => `${d.decade}s ${d.reports}`).join(" · "), ``);
  }

  out.push(`## 3. Drilling summary`, ``);
  if (expl.length) {
    out.push(mdTable(["Method", "Holes", "Metres", "Avg m", "Deepest m"],
      [...expl.map((h) => [HOLETYPE_LABELS[h.holetype] ?? h.holetype, n(h.holes), n(h.total_m), h.avg_m ?? "", h.max_m ?? ""]),
       ["**Exploration total**", n(expl.reduce((a, h) => a + h.holes, 0)), n(totalM), "", ""]]), ``);
    const bmd = brief.drilling.byMethodDecade;
    if (bmd.length) {
      const decades = [...new Set(bmd.map((d) => d.decade))].sort((a, b) => a - b);
      const methods = [...new Set(bmd.map((d) => d.holetype))].filter((h) => !EXCLUDED.includes(h));
      out.push(`Holes by method and decade drilled:`, ``);
      out.push(mdTable(["Method", ...decades.map((d) => `${d}s`)],
        methods.map((m) => [HOLETYPE_LABELS[m] ?? m, ...decades.map((d) => bmd.find((x) => x.holetype === m && x.decade === d)?.holes ?? "")])), ``);
    }
    if (brief.drilling.depthBuckets.length) {
      out.push(`Depth distribution: ` + brief.drilling.depthBuckets.map((b) => `${b.bucket} m: ${n(b.holes)}`).join(" · "), ``);
    }
    const dp = brief.drilling.deepest;
    if (dp) out.push(`Deepest recorded hole: **${n(Math.round(dp.maxdepth))} m**` +
      (dp.holeid ? ` (${dp.holeid}${dp.holetype ? `, ${methodName(dp.holetype)}` : ""}${dp.year ? `, ${dp.year}` : ""})` : "") +
      (dp.anumber ? `, reported in [A${dp.anumber}](https://wamex.dmp.wa.gov.au/Wamex/Search/ReportDetails?ANumber=${dp.anumber})` : "") + `.`, ``);
  } else out.push(`_No exploration drillhole is recorded in this area._`, ``);

  out.push(`## 4. Commodity focus over time`, ``);
  const cbd = brief.commodityByDecade;
  if (cbd.length) {
    const decades = [...new Set(cbd.map((c) => c.decade))].sort((a, b) => a - b);
    const names = [...new Set(cbd.map((c) => c.name))];
    out.push(mdTable(["Commodity", ...decades.map((d) => `${d}s`)],
      names.map((c) => [c.toLowerCase(), ...decades.map((d) => cbd.find((x) => x.name === c && x.decade === d)?.reports ?? "")])), ``);
  } else out.push(`_No report here names a target commodity._`, ``);
  if (brief.activity.length) {
    out.push(`Recorded activity (department controlled vocabulary): ` +
      brief.activity.slice(0, 18).map((a) => `${a.term} ${a.reports}`).join(" · "), ``);
  }

  out.push(`## 5. What the record does not show`, ``);
  if (cov.cells > 0) {
    out.push(`- **Ground with no drilling.** On a ${n(cov.cell_m)} m grid (MGA zone ${cov.srid - 7800}, ${n(cov.cells)} cells), ` +
      `${n(cov.undrilled)} cells (${Math.round((100 * cov.undrilled) / cov.cells)}%) contain no exploration drillhole; ` +
      `${n(cov.no_deep_hole)} (${Math.round((100 * cov.no_deep_hole) / cov.cells)}%) have none reaching ${cov.bedrock_depth_m} m; ` +
      `${n(cov.no_bedrock_method)} (${Math.round((100 * cov.no_bedrock_method) / cov.cells)}%) have never been drilled by ${cov.bedrock_methods.map(methodName).join(", ")}. ` +
      `A cell counts as tested if any hole falls anywhere in it; water bores and costeans are not counted.`);
  }
  if (brief.gapDecades.length) out.push(`- **Decades with no report.** Nothing on open file is dated to the ${brief.gapDecades.map((d) => `${d}s`).join(", ")}.`);
  if (brief.notRecorded.methods.length) out.push(`- **Methods never used here.** No ${brief.notRecorded.methods.map(methodName).join(", ")} hole is recorded.`);
  if (brief.notRecorded.commodities.length) out.push(`- **Commodities no report lists as a target.** ${brief.notRecorded.commodities.map((c) => c.toLowerCase()).join(", ")} (from a fixed list of 23).`);
  out.push(`- **Confidential work.** Annual reports stay confidential for five years (or until three months after surrender); surrender reports are released three months after surrender. Latest open-file release here: ${p.latest_release?.slice(0, 10) ?? "—"}.`);
  out.push(`- **Assays and geology.** The drillhole register holds collar position, depth, method and date only.`);
  if (brief.reportsCapped) out.push(`- **Inventory cut.** Section 6 lists the ${n(brief.reports.length)} most recent of ${n(s.report_count)} reports; the counts above use all of them.`);
  out.push(``);

  out.push(`## 6. Report inventory`, ``);
  for (const r of brief.reports) {
    out.push(`### [A${r.anumber}](${reportUrl(r)}) · ${r.report_year ?? "—"}${r.report_type ? ` · ${r.report_type}` : ""}`, ``);
    out.push(`**${r.title ?? "(untitled)"}**` + (r.operator ? `  \n${r.operator}` : "") +
      (r.coverage_pct != null ? `  \nCovers ${r.coverage_pct === 0 ? "<1" : r.coverage_pct}% of this area` + (r.footprint_km2 != null ? ` · ${r.footprint_km2} km² footprint` : "") : ""), ``);
    const abs = r.abstract_full ?? r.abstract_short;
    if (abs) out.push(`> ${abs.replace(/\n/g, "\n> ")}${!r.abstract_full && (r.abstract_short?.length ?? 0) >= 245 ? "…" : ""}`, ``);
    else out.push(`_No abstract in the bulk data._`, ``);
  }

  out.push(`---`, ``, `_${SOURCE_NOTE}_`, ``, ...attributionLines(brief, meta).map((l) => `_${l}_`),
    ``, `_This document is a summary of public records and makes no statement about prospectivity or value. Verify against the primary sources before relying on it._`, ``);
  return out.join("\n");
}
